version: "3.3"
services:
  redis1:
    image: redis
    ports:
       - "6379:6379"
    volumes:
      - "./conf/redis-01.conf:/usr/local/etc/redis/redis.conf"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: "host"

  redis2:
    image: redis
    volumes:
      - "./conf/redis-02.conf:/usr/local/etc/redis/redis.conf"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: "host"

  redis3:
    image: redis
    volumes:
      - "./conf/redis-03.conf:/usr/local/etc/redis/redis.conf"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    network_mode: "host"

 


